#Parallel Search Engine \u2014 Index Snapshot
#Fri Jun 19 13:57:24 IST 2026
D\:\\Projects\\GDoc\\.vscode\\settings.json=1770238490450
D\:\\Projects\\GDoc\\GDoc_Project_Decision_Summary.md=1781152567663
D\:\\Projects\\GDoc\\IDE_time_tracker-documentation.md=1780045406757
D\:\\Projects\\GDoc\\README.md=1772907095286
D\:\\Projects\\GDoc\\TestConnection.java=1780046030226
D\:\\Projects\\GDoc\\dependency-reduced-pom.xml=1780045283432
D\:\\Projects\\GDoc\\gdoc-model-final\\config.json=1781695068225
D\:\\Projects\\GDoc\\gdoc-model-final\\generation_config.json=1781695068209
D\:\\Projects\\GDoc\\gdoc-model-final\\tokenizer.json=1781695068193
D\:\\Projects\\GDoc\\gdoc-model-final\\tokenizer_config.json=1781695068209
D\:\\Projects\\GDoc\\gdoc-service\\main.py=1775590156096
D\:\\Projects\\GDoc\\pom.xml=1780045373589
D\:\\Projects\\GDoc\\src\\main\\generated-sources\\in\\sukruta\\gdoc\\Version.java=1780045281233
D\:\\Projects\\GDoc\\src\\main\\java\\in\\sukruta\\gdoc\\DocumentationGenerator.java=1780045709510
D\:\\Projects\\GDoc\\src\\main\\java\\in\\sukruta\\gdoc\\FileExtractor.java=1780044244380
D\:\\Projects\\GDoc\\src\\main\\java\\in\\sukruta\\gdoc\\Main.java=1781718234696
D\:\\Projects\\GDoc\\src\\main\\java\\in\\sukruta\\gdoc\\ModelAPIClient.java=1780045685991
D\:\\Projects\\GDoc\\src\\main\\java\\in\\sukruta\\gdoc\\clone_repo.java=1772907095311
D\:\\Projects\\GDoc\\src\\main\\java\\in\\sukruta\\gdoc\\repo_ingestion.java=1780029218380
D\:\\Projects\\GDoc\\src\\main\\resources\\logback.xml=1769174490175
D\:\\Projects\\GDoc\\target\\classes\\logback.xml=1769174490175
D\:\\Projects\\GDoc\\web-scraper-documentation.md=1781852210861
